# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_cfd7be4f3e43d5a4e5745b7051b1799d3a537caf

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client
